NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 1
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.3
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.4
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_A = 0.9


NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.1
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_A = 1

NDefines_Graphics.NGraphics.COUNTRY_COLOR_HUE_MODIFIER = 0.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 1.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 1.0
NDefines_Graphics.NGraphics.COUNTRY_UI_COLOR_HUE_MODIFIER = 0.0
NDefines_Graphics.NGraphics.COUNTRY_UI_COLOR_SATURATION_MODIFIER = 1.0
NDefines_Graphics.NGraphics.COUNTRY_UI_COLOR_BRIGHTNESS_MODIFIER = 1.0